name: deploy_image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  KEPTN_VERSION: 0.8.7
  
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    env:      
      KEPTN_ENDPOINT: ${{ secrets.KEPTN_ENDPOINT }}
      KEPTN_API_TOKEN: ${{ secrets.KEPTN_API_TOKEN }}
      
    steps:
      - name: Set up Keptn CLI
        run: |
          echo "Setting up keptn CLI $KEPTN_VERSION"
          curl -sL https://get.keptn.sh | KEPTN_VERSION=$KEPTN_VERSION bash
          keptn auth --endpoint=$KEPTN_ENDPOINT --api-token=$KEPTN_API_TOKEN
          keptn version
